<?
 header("Content-Type:text/html;   charset='utf8'"); 
 require_once '../../PHPExcel/Classes/PHPExcel.php';
 require_once '../../PHPExcel/Classes/PHPExcel/IOFactory.php';
 require_once '../../PHPExcel/Classes/PHPExcel/Writer/Excel5.php';
 require_once '../../PHPExcel/Classes/PHPExcel/Writer/Excel2007.php'; 
 require_once("../Db.php");
//新建 
$resultPHPExcel = new PHPExcel(); 
$resultPHPExcel->setActiveSheetIndex(0);  
$DB= new DB_MYSQL(); //连接数据库
//设置Excel文件属性
$objProps = $resultPHPExcel->getProperties(); 
$objProps->setCreator("2645-6"); 
$objProps->setLastModifiedBy("2645-6"); 
$objProps->setTitle("2645 Class Management System Export File"); 
$objProps->setSubject("2645 Class Management System Export File"); 
$objProps->setDescription("2645 Class Management System Export File, generated by PHPExcel."); 
$objProps->setKeywords("2645 Class Management System"); 
$objProps->setCategory("Class Management"); 
//设置表头 
$resultPHPExcel->getActiveSheet()->setCellValue('A1', '学期ID'); 
$resultPHPExcel->getActiveSheet()->setCellValue('B1', '学期名称');  
$resultPHPExcel->getActiveSheet()->setCellValue('C1', '开始日期');  
$resultPHPExcel->getActiveSheet()->setCellValue('D1', '结束日期');  
//设置列宽度
$resultPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(40);
$resultPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(12);
$resultPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(12);
//设置字体字号加粗
//$resultPHPExcel->getActiveSheet()->getDefaultStyle()->getFont()->setSize(10);
$resultPHPExcel->getActiveSheet()->getStyle('A1:D1')->getFont()->setBold(true);
//$resultPHPExcel->getActiveSheet()->getStyle('A1:E1')->getFont()->getColor()->setARGB('#FFFF0000');
$resultPHPExcel->getActiveSheet()->getStyle('A1:D1')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
//设置填充的样式和背景色
//$resultPHPExcel->getActiveSheet()->getStyle( 'A1:E1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
//$resultPHPExcel->getActiveSheet()->getStyle( 'A1:E1')->getFill()->getStartColor()->setARGB('#FF6495ED');
//显示网格线: 
$resultPHPExcel->getActiveSheet()->setShowGridlines(true);
//读取数据库，生成Excel表格
$i = 2; 
$items= $DB->get_all("select * from term");
foreach($items as $k=>$v){ 
	$resultPHPExcel->getActiveSheet()->setCellValue('A' . $i, $v['term']);
	$resultPHPExcel->getActiveSheet()->setCellValue('B' . $i, $v['term_name']); 
	$resultPHPExcel->getActiveSheet()->setCellValue('C' . $i, $v['startdate']); 
	$resultPHPExcel->getActiveSheet()->setCellValue('D' . $i, $v['enddate']); 
	$i++; 
}
//设置导出文件名 
$outputFileName = 'export.xls'; 
$objWriter = new PHPExcel_Writer_Excel5($resultPHPExcel); 
//$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
//ob_start(); ob_flush(); 
ob_end_clean();//清除缓冲区,避免乱码
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');  
header('Content-Disposition: attachment;filename="'.$outputFileName.'"');  
header('Cache-Control: max-age=0');  
//$objWriter = PHPExcel_IOFactory::createWriter($objExcel, 'Excel5');  
$objWriter->save('php://output');  
exit;  
?>